version = 1

[[annotations]]
path = [
    ".pre-commit-config.yaml",
    ".clang-format",
    ".gitignore",
    "*.md",
    "test/corpus.txt",
    "CMakeLists.txt",
    "include/**",
    "src/**",
    "test/**",
    "bench/**",
    "bindings/**",
    "scripts/**",
    "pyproject.toml",
    "setup.py",
]
SPDX-FileCopyrightText = "2026 ixsimpl contributors"
SPDX-License-Identifier = "Apache-2.0"
