version = 1

[[annotations]]
path = [
    "*.md",
    ".clang-format",
    ".gitignore",
    "ixsimpl_amalg.c",
    "test/corpus.txt",
    "test/corpus_assumptions.txt",
    "test/corpus_expected.txt",
    "scripts/requirements-gen.txt",
]
SPDX-FileCopyrightText = "2026 ixsimpl contributors"
SPDX-License-Identifier = "Apache-2.0"
