from typing import List, Optional, Sequence, Union

INT: int
RAT: int
SYM: int
ADD: int
MUL: int
FLOOR: int
CEIL: int
MOD: int
PIECEWISE: int
MAX: int
MIN: int
XOR: int
CMP: int
AND: int
OR: int
NOT: int
TRUE: int
FALSE: int
ERROR: int
PARSE_ERROR: int

class Expr:
    @property
    def is_error(self) -> bool: ...
    @property
    def is_parse_error(self) -> bool: ...
    @property
    def is_domain_error(self) -> bool: ...
    @property
    def tag(self) -> int: ...
    def simplify(
        self, *, assumptions: Optional[Sequence["Expr"]] = None
    ) -> "Expr": ...
    def to_c(self) -> str: ...
    def subs(self, var: str, replacement: Union["Expr", int]) -> "Expr": ...
    def __add__(self, other: Union["Expr", int]) -> "Expr": ...
    def __radd__(self, other: Union["Expr", int]) -> "Expr": ...
    def __sub__(self, other: Union["Expr", int]) -> "Expr": ...
    def __rsub__(self, other: Union["Expr", int]) -> "Expr": ...
    def __mul__(self, other: Union["Expr", int]) -> "Expr": ...
    def __rmul__(self, other: Union["Expr", int]) -> "Expr": ...
    def __truediv__(self, other: Union["Expr", int]) -> "Expr": ...
    def __rtruediv__(self, other: Union["Expr", int]) -> "Expr": ...
    def __neg__(self) -> "Expr": ...
    def __ge__(self, other: Union["Expr", int]) -> "Expr": ...
    def __gt__(self, other: Union["Expr", int]) -> "Expr": ...
    def __le__(self, other: Union["Expr", int]) -> "Expr": ...
    def __lt__(self, other: Union["Expr", int]) -> "Expr": ...
    def __eq__(self, other: object) -> bool: ...  # type: ignore[override]
    def __ne__(self, other: object) -> bool: ...  # type: ignore[override]
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __bool__(self) -> bool: ...

class Context:
    def __init__(self) -> None: ...
    def sym(self, name: str) -> Expr: ...
    def parse(self, input: str) -> Expr: ...
    def int_(self, val: int) -> Expr: ...
    def rat(self, p: int, q: int) -> Expr: ...
    def true_(self) -> Expr: ...
    def false_(self) -> Expr: ...
    def eq(self, a: Union[Expr, int], b: Union[Expr, int]) -> Expr: ...
    def ne(self, a: Union[Expr, int], b: Union[Expr, int]) -> Expr: ...
    def simplify_batch(
        self,
        exprs: List[Expr],
        *,
        assumptions: Optional[Sequence[Expr]] = None,
    ) -> None: ...
    def clear_errors(self) -> None: ...
    @property
    def errors(self) -> List[str]: ...

def floor(expr: Expr) -> Expr: ...
def ceil(expr: Expr) -> Expr: ...
def mod(a: Expr, b: Union[Expr, int]) -> Expr: ...
def max_(a: Expr, b: Union[Expr, int]) -> Expr: ...
def min_(a: Expr, b: Union[Expr, int]) -> Expr: ...
def xor_(a: Expr, b: Union[Expr, int]) -> Expr: ...
def same_node(a: Expr, b: Expr) -> bool: ...
