from collections.abc import Sequence

INT: int
RAT: int
SYM: int
ADD: int
MUL: int
FLOOR: int
CEIL: int
MOD: int
PIECEWISE: int
MAX: int
MIN: int
XOR: int
CMP: int
AND: int
OR: int
NOT: int
TRUE: int
FALSE: int
ERROR: int
PARSE_ERROR: int

CMP_GT: int
CMP_GE: int
CMP_LT: int
CMP_LE: int
CMP_EQ: int
CMP_NE: int

class Expr:
    @property
    def is_error(self) -> bool: ...
    @property
    def is_parse_error(self) -> bool: ...
    @property
    def is_domain_error(self) -> bool: ...
    @property
    def tag(self) -> int: ...
    @property
    def nchildren(self) -> int: ...
    @property
    def children(self) -> tuple[Expr, ...]: ...
    def child(self, i: int) -> Expr: ...
    @property
    def sym_name(self) -> str: ...
    @property
    def rat_num(self) -> int: ...
    @property
    def rat_den(self) -> int: ...
    @property
    def mul_nfactors(self) -> int: ...
    def mul_factor_exp(self, i: int) -> int: ...
    @property
    def cmp_op(self) -> int: ...
    def simplify(self, *, assumptions: Sequence[Expr] | None = None) -> Expr: ...
    def to_c(self) -> str: ...
    def subs(self, target: str | Expr, replacement: Expr | int) -> Expr: ...
    def __add__(self, other: Expr | int) -> Expr: ...
    def __radd__(self, other: Expr | int) -> Expr: ...
    def __sub__(self, other: Expr | int) -> Expr: ...
    def __rsub__(self, other: Expr | int) -> Expr: ...
    def __mul__(self, other: Expr | int) -> Expr: ...
    def __rmul__(self, other: Expr | int) -> Expr: ...
    def __truediv__(self, other: Expr | int) -> Expr: ...
    def __rtruediv__(self, other: Expr | int) -> Expr: ...
    def __neg__(self) -> Expr: ...
    def __ge__(self, other: Expr | int) -> Expr: ...
    def __gt__(self, other: Expr | int) -> Expr: ...
    def __le__(self, other: Expr | int) -> Expr: ...
    def __lt__(self, other: Expr | int) -> Expr: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __bool__(self) -> bool: ...

class Context:
    def __init__(self) -> None: ...
    def sym(self, name: str) -> Expr: ...
    def parse(self, input: str) -> Expr: ...
    def int_(self, val: int) -> Expr: ...
    def rat(self, p: int, q: int) -> Expr: ...
    def true_(self) -> Expr: ...
    def false_(self) -> Expr: ...
    def eq(self, a: Expr | int, b: Expr | int) -> Expr: ...
    def ne(self, a: Expr | int, b: Expr | int) -> Expr: ...
    def simplify_batch(
        self,
        exprs: list[Expr],
        *,
        assumptions: Sequence[Expr] | None = None,
    ) -> None: ...
    def clear_errors(self) -> None: ...
    @property
    def errors(self) -> list[str]: ...

def floor(expr: Expr) -> Expr: ...
def ceil(expr: Expr) -> Expr: ...
def mod(a: Expr, b: Expr | int) -> Expr: ...
def max_(a: Expr, b: Expr | int) -> Expr: ...
def min_(a: Expr, b: Expr | int) -> Expr: ...
def xor_(a: Expr, b: Expr | int) -> Expr: ...
def and_(a: Expr, b: Expr | int) -> Expr: ...
def or_(a: Expr, b: Expr | int) -> Expr: ...
def not_(a: Expr) -> Expr: ...
def pw(*branches: tuple[Expr | int, Expr | int]) -> Expr: ...
def same_node(a: Expr, b: Expr) -> bool: ...
