# SPDX-FileCopyrightText: 2026 ixsimpl contributors
# SPDX-License-Identifier: Apache-2.0
from collections.abc import Sequence
from fractions import Fraction
from typing import Literal, Self, TypeVar, overload

# Assumption inputs accept CMP/boolean roots and AND trees with those leaves.
# Unsupported predicate shapes raise ValueError.

INT: int
RAT: int
SYM: int
ADD: int
MUL: int
FLOOR: int
CEIL: int
MOD: int
PIECEWISE: int
MAX: int
MIN: int
XOR: int
CMP: int
AND: int
OR: int
NOT: int
ERROR: int
PARSE_ERROR: int

CMP_GT: int
CMP_GE: int
CMP_LT: int
CMP_LE: int
CMP_EQ: int
CMP_NE: int

class _Expr:
    @property
    def is_error(self) -> bool: ...
    @property
    def is_parse_error(self) -> bool: ...
    @property
    def is_domain_error(self) -> bool: ...
    @property
    def is_expr(self) -> bool: ...
    @property
    def is_pred(self) -> bool: ...
    @property
    def is_integer_valued(self) -> bool: ...
    @property
    def tag(self) -> int: ...
    @property
    def node_ptr(self) -> int: ...
    @property
    def nchildren(self) -> int: ...
    @property
    def children(self) -> tuple[Self, ...]: ...
    def child(self, i: int) -> Self: ...
    @property
    def sym_name(self) -> str: ...
    @property
    def rat_num(self) -> int: ...
    @property
    def rat_den(self) -> int: ...
    @property
    def add_coeff(self) -> Self: ...
    @property
    def add_nterms(self) -> int: ...
    def add_term(self, i: int) -> Self: ...
    def add_term_coeff(self, i: int) -> Self: ...
    @property
    def mul_coeff(self) -> Self: ...
    @property
    def mul_nfactors(self) -> int: ...
    def mul_factor_base(self, i: int) -> Self: ...
    def mul_factor_exp(self, i: int) -> int: ...
    @property
    def pw_ncases(self) -> int: ...
    def pw_value(self, i: int) -> Self: ...
    def pw_cond(self, i: int) -> Self: ...
    @property
    def cmp_op(self) -> int: ...
    def simplify(
        self,
        *,
        assumptions: Sequence[Self] | None = None,
        facts: Facts | None = None,
    ) -> Self: ...
    def expand(self) -> Self: ...
    def to_c(self) -> str: ...
    @overload
    def subs(self, target: str | Self, replacement: Self | int) -> Self: ...
    @overload
    def subs(self, mapping: dict[str | Self, Self | int]) -> Self: ...
    def __add__(self, other: Self | int) -> Self: ...
    def __radd__(self, other: Self | int) -> Self: ...
    def __sub__(self, other: Self | int) -> Self: ...
    def __rsub__(self, other: Self | int) -> Self: ...
    def __mul__(self, other: Self | int) -> Self: ...
    def __rmul__(self, other: Self | int) -> Self: ...
    def __truediv__(self, other: Self | int) -> Self: ...
    def __rtruediv__(self, other: Self | int) -> Self: ...
    def __mod__(self, other: Self | int) -> Self: ...
    def __rmod__(self, other: Self | int) -> Self: ...
    def __and__(self, other: Self | int) -> Self: ...
    def __rand__(self, other: Self | int) -> Self: ...
    def __or__(self, other: Self | int) -> Self: ...
    def __ror__(self, other: Self | int) -> Self: ...
    def __neg__(self) -> Self: ...
    def __ge__(self, other: Self | int) -> Self: ...
    def __gt__(self, other: Self | int) -> Self: ...
    def __le__(self, other: Self | int) -> Self: ...
    def __lt__(self, other: Self | int) -> Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __bool__(self) -> bool: ...
    @property
    def _ctx(self) -> Context: ...

_BatchExpr = TypeVar("_BatchExpr", bound=_Expr)

class Facts:
    def assume(self, pred: _Expr) -> None: ...
    def assume_many(self, predicates: Sequence[_Expr]) -> None: ...
    def assume_range(
        self,
        expr: _Expr,
        lower: int | Fraction | None = None,
        upper: int | Fraction | None = None,
    ) -> None: ...
    def derive_affine(
        self,
        base: _Expr,
        scale: int,
        offset: int,
        derived: _Expr,
    ) -> None: ...
    @overload
    def subs(self, target: str | _Expr, replacement: _Expr | int) -> Self: ...
    @overload
    def subs(self, mapping: dict[str | _Expr, _Expr | int]) -> Self: ...

class Context:
    def __init__(self) -> None: ...
    def sym(self, name: str) -> _Expr: ...
    def parse(self, input: str) -> _Expr: ...
    def parse_expr(self, input: str) -> _Expr: ...
    def parse_pred(self, input: str) -> _Expr: ...
    def int_(self, val: int) -> _Expr: ...
    def rat(self, p: int, q: int) -> _Expr: ...
    def true_(self) -> _Expr: ...
    def false_(self) -> _Expr: ...
    def facts(self) -> Facts: ...
    def import_(self, expr: _Expr) -> _Expr: ...
    def serialize(self, expr: _Expr) -> bytes: ...
    def deserialize(self, data: bytes | bytearray | memoryview) -> _Expr: ...
    def eq(self, a: _Expr | int, b: _Expr | int) -> _Expr: ...
    def ne(self, a: _Expr | int, b: _Expr | int) -> _Expr: ...
    def check(
        self,
        expr: _Expr,
        *,
        assumptions: Sequence[_Expr] | None = None,
        facts: Facts | None = None,
    ) -> bool | None: ...
    def integer_valued(
        self,
        expr: _Expr,
        *,
        assumptions: Sequence[_Expr] | None = None,
        facts: Facts | None = None,
    ) -> bool | None: ...
    def defined(
        self,
        expr: _Expr,
        *,
        assumptions: Sequence[_Expr] | None = None,
        facts: Facts | None = None,
    ) -> bool | None: ...
    def check_predicate(self, predicate: _Expr, facts: Facts) -> bool | None: ...
    def equivalent(self, lhs: _Expr, rhs: _Expr, facts: Facts) -> bool | None: ...
    def equivalent_finite_domain(
        self, lhs: _Expr, rhs: _Expr, facts: Facts, remaining_points: int
    ) -> tuple[bool | None, int]: ...
    def constant_difference(self, lhs: _Expr, rhs: _Expr, facts: Facts) -> int | None: ...
    def affine_decompose(
        self, expr: _Expr, symbol: _Expr, facts: Facts
    ) -> tuple[_Expr, _Expr] | None: ...
    def decompose_exact_quotient(self, expr: _Expr, facts: Facts) -> tuple[_Expr, _Expr] | None: ...
    def finite_difference(
        self, expr: _Expr, symbol: _Expr, step: _Expr, facts: Facts
    ) -> _Expr | None: ...
    def split_additive_constant(self, expr: _Expr, facts: Facts) -> tuple[_Expr, int] | None: ...
    def divisible(self, expr: _Expr, modulus: int, facts: Facts) -> bool | None: ...
    def known_bits(
        self, expr: _Expr, facts: Facts
    ) -> tuple[int, int, Literal["or_zero", "positive"] | None] | None: ...
    def symbol_congruence(self, symbol: _Expr, facts: Facts) -> tuple[int, int] | None: ...
    def congruent(self, expr: _Expr, modulus: int, residue: int, facts: Facts) -> bool | None: ...
    def try_exact_divide(
        self, expr: _Expr, divisor: int, facts: Facts
    ) -> tuple[Literal["proven", "not_exact", "unknown"], _Expr | None]: ...
    def pow2_fact(
        self,
        expr: _Expr,
        *,
        assumptions: Sequence[_Expr] | None = None,
        facts: Facts | None = None,
    ) -> Literal["or_zero", "positive"] | None: ...
    def range(
        self,
        expr: _Expr,
        *,
        assumptions: Sequence[_Expr] | None = None,
        facts: Facts | None = None,
    ) -> tuple[int | Fraction | None, int | Fraction | None] | None:
        """Infer bounds through supported powers, XOR, and first-match Piecewise."""

    def integer_range(
        self,
        expr: _Expr,
        *,
        assumptions: Sequence[_Expr] | None = None,
        facts: Facts | None = None,
    ) -> tuple[int | None, int | None] | None:
        """Infer bounds after proving the expression total and integer-valued."""

    def simplify_batch(
        self,
        exprs: list[_BatchExpr],
        *,
        assumptions: Sequence[_Expr] | None = None,
        facts: Facts | None = None,
    ) -> None: ...
    def clear_errors(self) -> None: ...
    @property
    def errors(self) -> list[str]: ...
    def stats(self) -> dict[str, int]: ...
    def stats_reset(self) -> None: ...

def floor(expr: _Expr) -> _Expr: ...
def ceil(expr: _Expr) -> _Expr: ...
def mod(a: _Expr, b: _Expr | int) -> _Expr: ...
def max_(a: _Expr, *args: _Expr | int) -> _Expr: ...
def min_(a: _Expr, *args: _Expr | int) -> _Expr: ...
def xor_(a: _Expr, *args: _Expr | int) -> _Expr: ...
def and_(a: _Expr, *args: _Expr | int) -> _Expr: ...
def or_(a: _Expr, *args: _Expr | int) -> _Expr: ...
def not_(a: _Expr) -> _Expr: ...
def pw(*branches: tuple[_Expr | int, _Expr | int]) -> _Expr: ...
def same_node(a: _Expr, b: _Expr) -> bool: ...
def _set_expr_class(cls: type[_Expr]) -> None: ...
